GoogleMap/Controllers/GoogleMapController.cs
using NHibernate.Mapping;
using StationServices.Models;
using StationServices.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GoogleMap.Controllers
{

    public class GoogleMapController : Controller
    {
        private StationService _stationService = new StationService();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetPoint()
        {
            var point = this._stationService.GetPoint();

            return Json(point, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetPolygon()
        {
            return Json(Session["polygons"], JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetRectangle()
        {
            return Json(Session["rectangle"], JsonRequestBehavior.AllowGet);
        }

        public ActionResult getCircle()
        {
            return Json(Session["circle"], JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveCircle(CircleModel circle)
        {
            List<CircleModel> list = Session["circle"] == null ? new List<CircleModel>() : (List<CircleModel>)Session["circle"];
            list.Add(circle);
            Session["circle"] = list;
            var data = _stationService.MapDataCircle(circle);
            AddTemp(data);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SavePolygon(LatLngModel[] polygons)
        {
            List<PolygonsModel> list = Session["polygons"] == null ? new List<PolygonsModel>() : (List<PolygonsModel>)Session["polygons"];
            list.Add(_stationService.GetPolygon(polygons));
            Session["polygons"] = list ;
            var data = _stationService.MapDataPolygon(polygons);
            AddTemp(data);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveRectangle(RectangleModel rectangle)
        {
            List<RectangleModel> list = Session["rectangle"] == null ? new List<RectangleModel>() : (List<RectangleModel>)Session["rectangle"];
            list.Add(rectangle);
            Session["rectangle"] = list;
            var data = _stationService.MapDataRectangle(rectangle);
            AddTemp(data);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public void AddTemp(DatatableModel data)
        {
            List<DatatableModel> listData = Session["temp"] == null ? new List<DatatableModel>() : (List<DatatableModel>)Session["temp"];
            listData.Add(data);
            Session["temp"] = listData;
        }
        public ActionResult GetTemp()
        {
            return Json(Session["temp"], JsonRequestBehavior.AllowGet);
        }


        public void SesionClear()
        {
            Session.Clear();
        }
        public ActionResult GetStation()
        {
            var model = this._stationService.GetStation();

            return Json(model, JsonRequestBehavior.AllowGet);
        }
    }
}

GoogleMap/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GoogleMap.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

GoogleMap/Views/Datatable/Index.cshtml
@{
    ViewBag.Title = "Index";
}



<table id="datatable_demo" class="display" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>Name</th>
            <th>Position</th>
            <th>Office</th>
            <th>Extn.</th>
            <th>Start date</th>
            <th>Salary</th>
        </tr>
    </thead>
</table>

@*<link href="~/Content/DataTables/css/jquery.dataTables.css" rel="stylesheet" />*@

@section css{
        @Styles.Render("~/Content/DataTables/css")
    }

@section scripts{
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/DataTables")
    @Scripts.Render("~/bundles/dataTablesDemo")
    <script type="text/javascript">
        "strict mode"
        let demo = null;
        $(document).ready(() => {
            demo = new DatatableDemo();
            demo.init();
        })
    </script>
}

GoogleMap/Views/GoogleMap/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
<meta charset="utf-8">
<div class="row">
    <table id="datatable_demo" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th rowspan="2">Name</th>
                <th colspan="4">Rectangle</th>
                <th colspan="3">Circle</th>
                <th colspan="2">Polygon</th>
            </tr>
            <tr>
                <th>north</th>
                <th>south</th>
                <th>east</th>
                <th>west</th>
                <th>center-lat</th>
                <th>center-lng</th>
                <th>radius</th>
                <th>lat-list</th>
                <th>lng-list</th>
            </tr>
        </thead>
    </table>
</div>
<div class="row">
    <div id="map"></div>
    <input type="button" id="Create" value="Drawing" />
    <input type="button" id="Clear" value="Clear" />
    <input type="button" id="Circle" value="วงกลม" />
    <input type="button" id="Polygon" value="โพลิก้อน" />
    <input type="button" id="Rectangle" value="สีเหลี่ยม" />

</div>
@section css{
    @Styles.Render("~/Content/DataTables/css")
}

@section scripts{
    @*<script src="@Url.Content("~/Scripts/googleMap/map.js")"></script>*@
    @Scripts.Render("~/bundles/googleMap")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/DataTables")

    <script type="text/javascript">
        let demo = null;
        $(document).ready(() => {
            demo = new DatatableDemo();
            demo.init();
        })
        function initMap() {
            let map = new Map();
            map.getPointUrl = '@Url.Action("GetPoint")';
            map.getPolygonUrl = '@Url.Action("GetPolygon")';
            map.getStationUrl = '@Url.Action("GetStation")';
            map.savePolygonUrl = '@Url.Action("SavePolygon")';
            map.saveCircleUrl = '@Url.Action("SaveCircle")';
            map.getCircleUrl = '@Url.Action("getCircle")';
            map.saveRectangleUrl = '@Url.Action("SaveRectangle")';
            map.getRectangleUrl = '@Url.Action("GetRectangle")';
            map.clear = '@Url.Action("SesionClear")';
            map.init();
        }
        

    </script>


    <script src="http://maps.google.com/maps/api/js?sensor=false&libraries=drawing&callback=initMap" async defer></script>
}

GoogleMap/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

GoogleMap/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

GoogleMap/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

GoogleMap/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @RenderSection("css", required: false)
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Map-Test", "Index", "GoogleMap")</li>
                    <li>@Html.ActionLink("DataTable-Test", "Index", "Datatable")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>